### ISSUE TITLE
IsEarlyClose not returning correct value years after 2029

### ISSUE THREAD

**Issue by vihaanthora** [scmhub/calendar#1]
### Description
The `IsEarlyClose` function does not return true for early close days for all years following 2030.

### Steps to recreate

```go
nyse := calendar.XNYS()

bodBlackFriday2030 := time.Date(2030, time.November, 29, 0, 0, 0, 0, calendar.NewYork)

fmt.Println(calendar.BlackFriday.Calc(2030, calendar.NewYork)) // prints 2030-11-29 00:00:00 -0500 EST
fmt.Println(bodBlackFriday2030)                                // prints 2030-11-29 00:00:00 -0500 EST

fmt.Println(nyse.IsEarlyClose(bodBlackFriday2030)) // prints false
```

**Comment by pchavanne** [comment]
Hello Vihaan,
Thank you for your feedback! By default, calendars are generated for a range of ±5 years around the current date.

- To adjust this, you can specify a custom start date (end date will be start date +10):
```go
nyse := calendar.XNYS(2025)  // which sets the end date to 2035
```
- Or define both start and end dates:
```go
nyse := calendar.XNYS(2010, 2050)
```

Here’s a quick fix:
```go
nyse := calendar.XNYS(2020, 2040)

bodBlackFriday2030 := time.Date(2030, time.November, 29, 0, 0, 0, 0, calendar.NewYork)

fmt.Println(calendar.BlackFriday.Calc(2030, calendar.NewYork)) // prints 2030-11-29 00:00:00 -0500 EST
fmt.Println(bodBlackFriday2030)                                // prints 2030-11-29 00:00:00 -0500 EST

fmt.Println(nyse.IsEarlyClose(bodBlackFriday2030)) // prints true
```
I will modify the code so that when a date is outside the calendar range, it resets the range, avoiding issues with holidays outside the defined range.

Thank you again for reporting the issue!

**Comment by pchavanne** [comment]
Hello Vihaan,

The code will panic when a time is outside the calendar's range because the user creates the calendar and knows its valid date range. Automatically adjusting the range would hide potential input mistakes (like typing 20500 instead of 2050) and could lead to inefficient behavior or unexpected results. Panicking ensures that errors are caught early, preventing silent issues and ensuring the calendar is used as intended.

**Comment by vihaanthora** [comment]
Hi Philippe,

Thanks for addressing this issue. My use case involves using the default range of the calendar (initializing the calendar object every time I want to determine if the current day is a holiday / early close), but I just wanted to test the library for future dates as well. 

Thanks for creating the best calendar library for Golang on all of GitHub!

**Comment by pchavanne** [comment]
I am very happy to help.
Thank you for your kind words.
